video_folder: './inputs/videos1/'
camera_parameters: './inputs/camera_parameters/Example1'
calibration_videos: './inputs/calibration/'
output_foldr: './outputs/'
model: './models/best.pt'

yolo_threshold: 0.5