parent_folder: 'D:/GoProMocapSystem/data'
camera_parameters: 'D:/AruCo_Calibration-main/camera_matrix/Example'
calibration_videos: './inputs/calibration/'
output_foldr: './outputs/'
model: './models/best.pt'

visualize: True
save_keypoints: True

yolo_threshold: 0.5